### ISSUE TITLE
Error en el carrito de compras

### ISSUE THREAD

**Issue by PabloT8** [PabloT8/eclothes#3]
A la hora de agregar el primer producto al carrito no lo toma en cuenta para la suma total de todos los productos

**Comment by PabloT8** [comment]
Ya solucionado

**Comment by LuisEsc14** [comment]
Hay que revisar la función donde se calcula ese precio total

**Comment by PabloT8** [comment]
[
![WhatsApp Image 2020-12-04 at 3 44 33 PM](https://user-images.githubusercontent.com/57971712/101838447-3fbb1580-3b06-11eb-9973-1e3f26dedb96.jpeg)
](url) 
Ya solucionado el conteo y suma total de los productos, aqui esta la vista corregida

**Comment by PabloT8** [comment]
[
![Solucion1](https://user-images.githubusercontent.com/57971712/101839339-d2a87f80-3b07-11eb-8a44-841d344996d3.jpg)
](url)
Ya concuerda la cantidad con la suma total de los productos, solucion cambiar ese item en el modelo carrito
